package model;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * @version  1.0
 * @author YuZheng
 * @Date 9/14/2015
 * 
 * This class is a option set class, it would store all option and provide many 
 * functions to deal with the option, ALL CRUD functions are provided.
 */ 

public class OptionSet implements Serializable{
	private static final long serialVersionUID = -7734178258610296612L;
	private String name;	// The option name
	private ArrayList<Option> opt;	// all option
	private Option choice;
	
	// construction
	protected OptionSet() {}
	
	protected OptionSet(String n) {
		this.opt = new ArrayList<Option>();
		this.name = n;
	}
	
	// All getters and setters generated by IDE
	protected String getName() {
		return name;
	}
	protected void setName(String name) {
		this.name = name;
	}

	protected ArrayList<Option> getOpt() {
		return opt;
	}

	protected void setOpt(ArrayList<Option> opt) {
		this.opt = opt;
	}
	
	/** 
	 * Additional getters and setters
	 */
	// get
	protected int getOptionSize() {
		return opt.size();
	}
	protected Option getOption(int index) {
		if (index < 0 || index > opt.size())
			return null;
		else {
			for (int i = 0; i < opt.size(); i++) {
				if (opt.get(index) != null)
					return opt.get(index);
			}
		}
		return null;
	}
	
	// get the option by name
	protected Option getOption (String name) {
		for (int i = 0; i < opt.size(); i++) {
			if (opt.get(i).getName().equals(name)) 
				return opt.get(i);
		}
		return null;
	}
	
	// set option by index
	protected void setOption (Option opt) {
		this.opt.add(opt);
	}
	protected void setOption (String name, float price) {
		this.opt.add(new Option(name, price));
	}
	
	// Delete option
	protected void deleteOption (int index) {
		if (index < 0 || index > opt.size())
			return;
		if (opt.get(index) != null) {
			opt.remove(index);
		}
	}
	
	protected void deleteOption (String name) {
		for (int i = 0; i < opt.size(); i++) {
			if (opt.get(i).getName().equals(name)) {
				opt.remove(i);
			}
		}
	}
	
	// Update option name only
	protected void updateOptionName (int index, String name) {
		if (index > opt.size() || index < 0)
			return;
		opt.get(index).setName(name);
	}
	protected void updateOptionName (String oldname, String name) {
		if (getOption(oldname) != null)
			getOption(oldname).setName(name);
	}
	
	// Update option
	protected void updateOption (int index, String name, float price) {
		if (index > opt.size() || index < 0)
			return;
		opt.get(index).setName(name);
		opt.get(index).setPrice(price);
	}
	protected void updateOption (String oldname, String name, float price) {
		if (getOption(oldname) != null) {
			getOption(oldname).setName(name);
			getOption(oldname).setPrice(price);
		}
	}
	
	// Update option price only
	protected void updateOptionprice (int index, float price) {
		if (getOption(index) != null)
			getOption(index).setPrice(price);
	}
	protected void updateOptionprice (String name, float price) {
		if (getOption(name) != null)
			getOption(name).setPrice(getOption(name).getPrice() + price);
	}
	
	// print funciton
	protected void printoption() {
		for (int i = 0; i < opt.size(); i++) {
			if (opt.get(i) != null) {
				System.out.println(i + ". " + opt.get(i).getName() + ": " + 
						"$" + opt.get(i).getPrice());
			}
		}
	}
	
	/**
	 * Process about choice
	 */
	protected void setChoice(String optionName) {
		choice = getOption(optionName);
	}
	protected String getChoiceName() {
		return choice.getName();
	}
	protected float getChoicePrice() {
		return choice.getPrice();
	}
	
	// inner class, which is store all option choices.
	protected class Option implements Serializable {
		private static final long serialVersionUID = -3381529312821940124L;
		private String name;	// The option name
		private float price;	// The option price
		
		// Construction
		protected Option(String name, float price) {
			this.name = name;
			this.price = price;
		}
		
		protected Option() {
		}
		
		// getters and setters
		protected String getName() {
			return name;
		}
		
		protected void setName(String name) {
			this.name = name;
		}
		
		protected float getPrice() {
			return price;
		}
		
		protected void setPrice(float price) {
			this.price = price;
		}	
	}
	
}
